provides:
  - bybit_to_tradingview

description: >
  Скрипт на Python для передачи данных из Bybit в TradingView.

homepage: https://github.com/vanobond/dtmain

versions:
  - 1.0.0

fetch:
  url: https://github.com/vanobond/dtmain/archive/refs/tags/v1.0.0.tar.gz
  sha256: e00f695ea39d24ee810f5c95bdf4d62f31f22afa370284421e064d80b8766dd5

build:
  script: |
    install -Dm755 bybit_to_tradingview.py $PREFIX/bin/bybit_to_tradingview
