provides:
  - bybit_to_tradingview

description: >
  Скрипт для передачи данных из Bybit в TradingView.

homepage: https://github.com/твой-логин/название-репозитория

versions:
  - 1.0.0

fetch:
  url: https://github.com/твой-логин/название-репозитория/archive/refs/tags/v1.0.0.tar.gz
  sha256: твоя_SHA256_сумма

build:
  script: |
    install -Dm755 bybit_to_tradingview.py $PREFIX/bin/bybit_to_tradingview
